export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const WEBINAR_START = "WEBINAR_START";
export const WEBINAR_SUCCESS = "WEBINAR_SUCCESS";
export const WEBINAR_FAIL = "WEBINAR_FAIL";
export const FETCH_WEBINAR_START = "FETCH_WEBINAR_START";
export const FETCH_WEBINAR_SUCCESS = "FETCH_WEBINAR_SUCCESS";
export const FETCH_WEBINAR_FAIL = "FETCH_WEBINAR_FAIL";

export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_DELETE = "CART_DELETE";
export const CART_FAIL = "CART_FAIL";
export const FETCH_CART_START = "FETCH_CART_START";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAIL = "FETCH_CART_FAIL";

export const BOOKMARK_START = "BOOKMARK_START";
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_DELETE = "BOOKMARK_DELETE";
export const BOOKMARK_FAIL = "BOOKMARK_FAIL";
export const FETCH_BOOKMARK_START = "FETCH_BOOKMARK_START";
export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS";
export const FETCH_BOOKMARK_FAIL = "FETCH_BOOKMARK_FAIL";

export const ORDER_START = "ORDER_START";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";
